### ISSUE TITLE
Exception when compiling CMS measure ProstateCaAvoidanceBoneScanOveruseFHIR-0.2.000

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-cql-sdk#147]
**Describe the bug**
``
Hl7.Cql.Compiler.ExpressionBuilder[0]
      Building expressions for ProstateCaAvoidanceBoneScanOveruseFHIR-0.2.000
warn: Hl7.Cql.Compiler.ExpressionBuilder[0]
      ProstateCaAvoidanceBoneScanOveruseFHIR-0.2.000 line 100:11-100:38: Potentially unsafe cast from Object to type CqlConcept
Unhandled exception. System.ArgumentException: Cannot convert System.Nullable`1[Hl7.Fhir.Model.ObservationStatus] to Hl7.Fhir.Model.Code`1[Hl7.Fhir.Model.ObservationStatus] (Parameter 'source')
   at Hl7.Cql.Compiler.CqlOperatorsBinding.BindConvert(MemberExpression operators, Expression source, Expression typeExpression) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/CqlOperatorsBinding.cs:line 752
   at Hl7.Cql.Compiler.CqlOperatorsBinding.Bind(CqlOperator operator, Expression runtimeContext, Expression[] parameters) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/CqlOperatorsBinding.cs:line 79
   at Hl7.Cql.Compiler.ExpressionBuilder.ChangeType(Expression input, Type outputType, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.TypeOperators.cs:line 254
   at Hl7.Cql.Compiler.ExpressionBuilder.PropertyHelper(Expression source, String path, Type expectedType, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 2312
   at Hl7.Cql.Compiler.ExpressionBuilder.Property(Property op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 2264
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 800
   at Hl7.Cql.Compiler.ExpressionBuilder.In(In e, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.IntervalOperators.cs:line 117
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 644
   at Hl7.Cql.Compiler.ExpressionBuilder.BinaryOperator(CqlOperator operator, BinaryExpression be, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 950
   at Hl7.Cql.Compiler.ExpressionBuilder.And(And e, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.LogicalOperators.cs:line 24
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 440
   at Hl7.Cql.Compiler.ExpressionBuilder.WithToSelectManyBody(String outerScope, Type outerElementType, RelationshipClause with, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 2056
   at Hl7.Cql.Compiler.ExpressionBuilder.SingleSourceQuery(Query query, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 1061
   at Hl7.Cql.Compiler.ExpressionBuilder.Query(Query query, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 1029
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 806
   at Hl7.Cql.Compiler.ExpressionBuilder.Last(Last e, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.ListOperators.cs:line 48
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 659
   at Hl7.Cql.Compiler.ExpressionBuilder.SingleSourceQuery(Query query, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 1043
   at Hl7.Cql.Compiler.ExpressionBuilder.Query(Query query, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 1029
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 806
   at Hl7.Cql.Compiler.ExpressionBuilder.Build() in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 360
   at Hl7.Cql.Packaging.LibraryPackager.PackageResources(DirectoryInfo elmDirectory, DirectoryInfo cqlDirectory, DirectedGraph packageGraph, TypeResolver typeResolver, OperatorBinding operatorBinding, TypeManager typeManager, Func`2 canon, ILoggerFactory logFactory) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Packaging/LibraryPackager.cs:line 157
   at Hl7.Cql.Packaging.ResourcePackager.Package(DirectoryInfo elmDir, DirectoryInfo cqlDir, Action`1 afterPackageMutator) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Packaging/ResourcePackager.cs:line 42
   at Hl7.Cql.Packager.Program.Package(DirectoryInfo elmDir, DirectoryInfo cqlDir, DirectoryInfo csDir, DirectoryInfo fhirDir) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/PackagerCLI/Program.cs:line 109
   at Hl7.Cql.Packager.Program.Main(String[] args) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/PackagerCLI/Program.cs:line 77
``

**To Reproduce**
Measures are committed to branch inspect-cms-measures. Executing the PackagerCli in that branch will trigger the error.

**Version used:**
Current develop version of the PackagerCli

**Comment by ewoutkramer** [comment]
The most important hint here is "Cannot convert System.Nullable`1[Hl7.Fhir.Model.ObservationStatus] to Hl7.Fhir.Model.Code`1[Hl7.Fhir.Model.ObservationStatus]".

During compilation, we convert from the actual .NET type encountered in the datasource to the CQL type that the engine uses, and vice versa. For example: there would be a conversion of the FHIR FhirDateTime to the CQL DateTime type. Both are .NET POCO's, but since the engine can handle different datamodels, it needs a mapping from the model in use (here: FHIR) to the internal CQL model (the set of CQL types: string, code, datetime etc).

This task is done by a model-specific converter factory, in this case the FhirTypeConverter.cs in Cql.Firely. The function "ConvertCodeTypes" auto-generates converters for each of the defines .NET enums to "CqlCode".  However, here we are looking for a conversion from an enum to a CqlConcept - which is not yet defined.
