### ISSUE TITLE
Exception when compiling CMS measure HFBetaBlockerTherapyforLVSDFHIR-1.3.000

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-cql-sdk#148]
Getting ArgumentException while building statement for definition 'Initial Population 'in library 'HFBetaBlockerTherapyforLVSDFHIR-1.3.000'. 

```
System.ArgumentException: Cannot resolve type for expression
   at Hl7.Cql.Compiler.TypeManager.TypeFor(Element element, ExpressionBuilderContext context, Boolean throwIfNotFound)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\TypeManager.cs:line 130
   at Hl7.Cql.Compiler.TypeManager.TypeFor(Element element, ExpressionBuilderContext context, Boolean throwIfNotFound)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\TypeManager.cs:line 104
   at Hl7.Cql.Compiler.ExpressionBuilder.Property(Property op, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 2266
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 803
   at Hl7.Cql.Compiler.ExpressionBuilder.Property(Property op, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 2247
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 803
   at Hl7.Cql.Compiler.ExpressionBuilder.CalculateAgeAt(CalculateAgeAt e, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.ClinicalOperators.cs:line 34
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 461
   at Hl7.Cql.Compiler.ExpressionBuilder.BinaryOperator(CqlOperator operator, BinaryExpression be, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 952
   at Hl7.Cql.Compiler.ExpressionBuilder.GreaterOrEqual(GreaterOrEqual e, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.ComparisonOperators.cs:line 123
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 608
   at Hl7.Cql.Compiler.ExpressionBuilder.BinaryOperator(CqlOperator operator, BinaryExpression be, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 952
   at Hl7.Cql.Compiler.ExpressionBuilder.And(And e, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.LogicalOperators.cs:line 24
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 443
   at Hl7.Cql.Compiler.ExpressionBuilder.BinaryOperator(CqlOperator operator, BinaryExpression be, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 952
   at Hl7.Cql.Compiler.ExpressionBuilder.And(And e, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.LogicalOperators.cs:line 24
   at Hl7.Cql.Compiler.ExpressionBuilder.TranslateExpression(Element op, ExpressionBuilderContext ctx)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 443
   at Hl7.Cql.Compiler.ExpressionBuilder.Build()
      in C:\Dev\firely-cql-sdk\Cql\Cql.Compiler\ExpressionBuilder.cs:line 363
   at Hl7.Cql.Packaging.LibraryPackager.PackageResources(DirectoryInfo elmDirectory, DirectoryInfo cqlDirectory, DirectedGraph packageGraph, TypeResolver typeResolver, OperatorBinding operatorBinding, TypeManager typeManager, Func`2 canon, ILoggerFactory logFactory)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Packaging\LibraryPackager.cs:line 161
   at Hl7.Cql.Packaging.ResourcePackager.PackageCore(DirectoryInfo elmDir, DirectoryInfo cqlDir, Action`1 afterPackageMutator, String resourceCanonicalRootUrl)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Packaging\ResourcePackager.cs:line 53
   at Hl7.Cql.Packaging.ResourcePackager.Package(PackageArgs args)
      in C:\Dev\firely-cql-sdk\Cql\Cql.Packaging\ResourcePackager.cs:line 42
   at Hl7.Cql.Packager.Program.Package(DirectoryInfo elmDir, DirectoryInfo cqlDir, DirectoryInfo csDir, DirectoryInfo fhirDir, String resourceCanonicalRootUrl)
      in C:\Dev\firely-cql-sdk\Cql\PackagerCLI\Program.cs:line 133
   at Hl7.Cql.Packager.Program.Main(String[] args)
      in C:\Dev\firely-cql-sdk\Cql\PackagerCLI\Program.cs:line 101
```

**To Reproduce**
Measures are committed to branch `inspect-cms-measures`. Executing the PackagerCli in that branch will trigger the error.

**Version used:**
Current develop version of the PackagerCli

**Comment by ewoutkramer** [comment]
The file `SupplementalDataElements.json`, which contains the ELM for the library with the same name has tons of nodes that are untyped. The first one that causes an error looks like this (inside a Query representing the CQL at line 30:3)

```
 {
                        "type" : "Query",
                        "source" : [ {
                           "alias" : "$this",
                           "expression" : {
                              "path" : "extension",
                              "type" : "Property",
                              "source" : {
                                 "name" : "Patient",
                                 "type" : "ExpressionRef"
                              }
                           }
                        }
```

In this ELM, we query over an `extension` property of the context `Patient`, referred to by the most inner node called `source`. We can see here an ELM node of type `ExpressionRef` that has no type annotation, in fact there is no other info than the name "Patient".

To support nodes without types, the ExpressionBuilder has a function called `TypeFor()` that tries to derive the type for the node, but currently, `TypeFor` does not know how to handle `ExpressionRef`s, so it cannot determine the type and then fails.

I am assuming this is a very common case and this is a prima candidate for fixing. To do so, we should add support for determining the type of an ExpressionRef - which should be easy since all expressions are listed in the ELM tree, and we could simply look it up (although overloads may complicate this - let's check how Evan handles this elsewhere).

**Comment by ewoutkramer** [comment]
Actually, the problem lies one level higher.  This is initially recognized as a "Property" expression by the code, so we end up in ` protected Expression Property(Property op, ExpressionBuilderContext ctx)`.

Within that function, the path of the property is checked (here: `extension`, trying to access Patient.extension):

```
  else if (op.source != null)
            {
                var source = TranslateExpression(op.source, ctx);
                var parts = path.Split('.');
                if (parts.Length > 1)
```

That last line reads `.Length > 1`, but in our case, we just have `expression`.  Looking at the code, I cannot yet understand why this would not just be `parts.Length > 0` (bascially, anything goes, second case not needed).  If I do that, the code continues (but fails on something else).

**Comment by baseTwo** [comment]
Taking notes as I go along.

```mermaid
flowchart TD
subgraph Include Graph for HFBetaBlockerTherapyforLVSDFHIR

HFBetaBlockerTherapyforLVSDFHIR --> FHIRHelpers
HFBetaBlockerTherapyforLVSDFHIR -- SDE --> SupplementalDataElements
HFBetaBlockerTherapyforLVSDFHIR --> QICoreCommon
HFBetaBlockerTherapyforLVSDFHIR -- AHA --> AHAOverall
AHAOverall --> FHIRHelpers
AHAOverall --> QICoreCommon
QICoreCommon --> FHIRHelpers
SupplementalDataElements --> FHIRHelpers

end
```
