### ISSUE TITLE
Exception when compiling QICoreCommon-2.0.000

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-cql-sdk#149]
**Describe the bug**
``
info: Hl7.Cql.Compiler.ExpressionBuilder[0]
      Building expressions for QICoreCommon-2.0.000
Unhandled exception. System.InvalidOperationException: Duplicate code detected: billing from Diagnosis Role (http://terminology.hl7.org/CodeSystem/diagnosis-role)
   at Hl7.Cql.Compiler.ExpressionBuilder.Build() in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Compiler/ExpressionBuilder.cs:line 169
   at Hl7.Cql.Packaging.LibraryPackager.PackageResources(DirectoryInfo elmDirectory, DirectoryInfo cqlDirectory, DirectedGraph packageGraph, TypeResolver typeResolver, OperatorBinding operatorBinding, TypeManager typeManager, Func`2 canon, ILoggerFactory logFactory) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Packaging/LibraryPackager.cs:line 157
   at Hl7.Cql.Packaging.ResourcePackager.Package(DirectoryInfo elmDir, DirectoryInfo cqlDir, Action`1 afterPackageMutator) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/Cql.Packaging/ResourcePackager.cs:line 42
   at Hl7.Cql.Packager.Program.Package(DirectoryInfo elmDir, DirectoryInfo cqlDir, DirectoryInfo csDir, DirectoryInfo fhirDir) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/PackagerCLI/Program.cs:line 109
   at Hl7.Cql.Packager.Program.Main(String[] args) in /Users/alex/Dev/Firely/SDK/firely-cql-sdk/Cql/PackagerCLI/Program.cs:line 77
``

**To Reproduce**
Measures are committed to branch inspect-cms-measures. Executing the PackagerCli in that branch will trigger the error.

**Version used:**
Current develop version of the PackagerCli

**Comment by ewoutkramer** [comment]
The code "billing" appears twice:

Once on line 35:
`code "Billing": 'billing' from "Diagnosis Role" display 'Billing'`

and once on line 93:
`code "billing": 'billing' from "Diagnosis Role" display 'billing diagnosis'`

Note that the display differs, but also the local name of the code, once `Billing` and once `billing`, so they differ in case.

The problem surfaces because in the *ELM*, the identifier for a code is actually its code, which *is* the same, so the ELM contains two "codes" with the same id - I think it's not unreasonable we catch this  - certainly since the introduced local name differ only in case, and there are inconsistent displays. It seems this is a human oversight.

So, what to do?  Looking at the CQL spec, it says:

> 1.9. Case-Sensitivity
To encourage consistency and reduce potential confusion, CQL is a case-sensitive language. This means that case is considered when matching keywords and identifiers in the language

It seems we need to take "billing" and "Billing" as separate codes, and so use the introduced local name, not the id as the unique key. Changing the dictionary lookup to do so is easy, but we should allow some time to find downstream bugs that maybe count on "id" being unique and/or the local name not being case-sensitive.
