### ISSUE TITLE
IndexedBundle not resolving reference for MedicationRequest - assumes CodeableConcept

### ISSUE THREAD

**Issue by richfirely** [FirelyTeam/firely-cql-sdk#263]
**Describe the bug**
When processing synthea files for **ColorectalCancerScreeningsFHIR-0.0.003** I get an exception in:
https://github.com/FirelyTeam/firely-cql-sdk/blob/7ff61c25eccdaff73d785f070fe84f8b1dd868c2/Cql/Cql.Firely/IndexedBundle.cs#L48

System.NotSupportedException
  HResult=0x80131515
  Message=Don't know how to derive a list of codings from type 'Hl7.Fhir.Model.ResourceReference'.
  Source=Hl7.Fhir.Base
  StackTrace:
   at Hl7.Fhir.Model.CodedExtensions.ToCodings(DataType dt)
   at Hl7.Cql.Fhir.IndexedBundle.<FilterByType>d__6`1.MoveNext() in E:\Source\Repos\firely-cql-sdk-2.0\Cql\Cql.Firely\IndexedBundle.cs:line 48
   at System.Linq.Enumerable.UnionIterator`1.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Hl7.Cql.Runtime.CqlOperators.ListUnion[T](IEnumerable`1 left, IEnumerable`1 right) in E:\Source\Repos\firely-cql-sdk-2.0\Cql\Cql.Operators\CqlOperators.ListOperators.cs:line 1169
   at AdvancedIllnessandFrailtyExclusionECQMFHIR4_5_17_000.Dementia_Medications_In_Year_Before_or_During_Measurement_Period_Value() in E:\Source\Repos\firely-cql-sdk-2.0\Demo\Measures\AdvancedIllnessandFrailtyExclusionECQMFHIR4-5.17.000.cs:line 227
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

**To Reproduce**
1. Run the CLI tool on the attached file:
` "commandLineArgs": "--l ColorectalCancerScreeningsFHIR-0.0.003 --d Joaquin141_Stiedemann542_0b1ccc6e-e03a-5bc7-7211-39b4119e58ea.json"`

**Expected behavior**
It appears to be assuming there will be medication codification, but that is a resource reference not a CodeableConcept in this particular MedicationRequest. The profile shows it could be either of these:
https://hl7.org/fhir/r4/medicationrequest.html

**Screenshots**
See attached file.
[Joaquin141_Stiedemann542_0b1ccc6e-e03a-5bc7-7211-39b4119e58ea.json](https://github.com/FirelyTeam/firely-cql-sdk/files/14787946/Joaquin141_Stiedemann542_0b1ccc6e-e03a-5bc7-7211-39b4119e58ea.json)

**Version used:**
 - Version: 1.0 & 2.0

**Additional context**

**Comment by ewoutkramer** [comment]
This is related to a bug in the SDK: https://github.com/FirelyTeam/firely-net-sdk/issues/2848

We'll be fixing that bug, and after the next SDK update, this should be gone.

**Comment by ewoutkramer** [comment]
See https://github.com/FirelyTeam/firely-net-sdk/pull/2849.
