### ISSUE TITLE
Fix integration test - Division of different units is not supported

### ISSUE THREAD

**Issue by cheng13231** [FirelyTeam/firely-cql-sdk#377]
**Describe the bug**

```
- High Risk Medications with Average Daily Dose Criteria: NotSupportedException - Division of different units is not supported; only division by a numeric value (units = "1") is supported.
- Numerator 1: NotSupportedException - Division of different units is not supported; only division by a numeric value (units = "1") is supported.
- Numerator 3: NotSupportedException - Division of different units is not supported; only division by a numeric value (units = "1") is supported.
   at IntegrationRunner.UseofHighRiskMedicationsintheElderlyFHIR.Population_FromResource(String testCaseId) in C:\Dev\FirelyTeam\firely-cql-sdk\Firely.Cql.Sdk.Integration.Runner\IntegrationRunner\tests\UseofHighRiskMedicationsintheElderlyFHIR.g.cs:line 81
   at InvokeStub_UseofHighRiskMedicationsintheElderlyFHIR.Population_FromResource(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

![image](https://github.com/FirelyTeam/firely-cql-sdk/assets/81763984/e2baf016-bdb8-4862-adc6-f1786e1cd9db)

**To Reproduce**
1. Run following integration test `UseofHighRiskMedicationsintheElderlyFHIR` -> test case `3201fe4a-d1b0-4296-a60e-8680247e8128`
2. See error
![image](https://github.com/FirelyTeam/firely-cql-sdk/assets/81763984/b96c7531-af65-48e2-9877-082505f226bb)

**Version used:**
 - Version: develop-2.0 (commit https://github.com/FirelyTeam/firely-cql-sdk/commit/25584e496722c12894d706b6757fd4cd0f52c074)

**Comment by baseTwo** [comment]
Confirmed in [latest](https://github.com/FirelyTeam/firely-cql-sdk/commit/db3f7f6a7af7ead501cfb2b822ad309b3d432dbb) develop-2.0 after mering in cql-to-elm.

**Comment by baseTwo** [comment]
The test no longer exists
